# Generated by Django 2.2.2 on 2019-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=64)),
                ('esal', models.IntegerField()),
                ('eaddress', models.CharField(max_length=64)),
                ('ephone', models.IntegerField()),
            ],
        ),
    ]
